name: main

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    name: Run
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11
          # java-version: |
          #   8
          #   11
          #   17
      - run: python3 -m pip install -r requirements.txt
      - run: python3 run.py
